### ISSUE TITLE
[Azure-Metrics-Exporter] Metrics Path from Probes Config not handled in Service Monitor endpoint path

### ISSUE THREAD

**Issue by logamanig** [webdevops/helm-charts#15]
Hi,

Azure-Metrics-Exporter metrics path config e.g /probe/metrics/list is not handled in the service. monitor created by the helm chart.

**Comment by anorm** [comment]
I'm wondering if I'm not using the helm chart as intended. I supply values:

```
prometheus:
  metricProbes:
    probes:
      - name: foo
        params:
          bar: baz
```

A `ServiceMonitor` CR is created as expected but it is impossible to target the correct path. @Wihrt's linked PR #17 seems to address the issue.

Is there anything I can do to get the chart working as expected in the current version (1.0.4) or anything I can do to help get this issue resolved?
