### ISSUE TITLE
[azure-metrics-exporter] add possibility to disable automount service account token

### ISSUE THREAD

**Issue by ewencodes** [webdevops/helm-charts#87]
Hi, we're using azure-metrics-exporter to export Azure Monitor metrics into our Prometheus and we want to disable automounting of serviceaccount token using `automountServiceAccountToken: false` flag.

```yaml
automountServiceAccountToken: false

serviceAccount:
  automountServiceAccountToken: false
```

Thx ;)
